"""Add slug fields

Revision ID: 179d4ebc2a7e
Revises: 202fa01d2fce
Create Date: 2022-09-29 09:10:12.277151

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = '179d4ebc2a7e'
down_revision = '202fa01d2fce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employer_record', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('employer_record', sa.Column('trade_name_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_employer_record_city'), 'employer_record', ['city'], unique=False)
    op.create_index(op.f('ix_employer_record_country'), 'employer_record', ['country'], unique=False)
    op.create_index(op.f('ix_employer_record_phone'), 'employer_record', ['phone'], unique=False)
    op.create_index(op.f('ix_employer_record_slug'), 'employer_record', ['slug'], unique=False)
    op.create_index(op.f('ix_employer_record_state'), 'employer_record', ['state'], unique=False)
    op.create_index(op.f('ix_employer_record_trade_name_slug'), 'employer_record', ['trade_name_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employer_record_trade_name_slug'), table_name='employer_record')
    op.drop_index(op.f('ix_employer_record_state'), table_name='employer_record')
    op.drop_index(op.f('ix_employer_record_slug'), table_name='employer_record')
    op.drop_index(op.f('ix_employer_record_phone'), table_name='employer_record')
    op.drop_index(op.f('ix_employer_record_country'), table_name='employer_record')
    op.drop_index(op.f('ix_employer_record_city'), table_name='employer_record')
    op.drop_column('employer_record', 'trade_name_slug')
    op.drop_column('employer_record', 'slug')
    # ### end Alembic commands ###
