"""Add visa class

Revision ID: faa4cd2a66f2
Revises: 7b7e117c0506
Create Date: 2022-09-27 12:54:23.774468

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = 'faa4cd2a66f2'
down_revision = '7b7e117c0506'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dol_disclosure_job_order', sa.Column('visa_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dol_disclosure_job_order', 'visa_class')
    # ### end Alembic commands ###
