version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cdm-data-hub"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-10eyc4nvnfgf2"
s3_prefix = "cdm-data-hub"
region = "us-east-2"
profile = "cdm"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
