"""Update address_record

Revision ID: 7b7e117c0506
Revises: a071f148eedc
Create Date: 2022-09-23 16:12:09.393810

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = '7b7e117c0506'
down_revision = 'a071f148eedc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address_record', sa.Column('normalized_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_address_record_address_1'), 'address_record', ['address_1'], unique=False)
    op.create_index(op.f('ix_address_record_address_2'), 'address_record', ['address_2'], unique=False)
    op.create_index(op.f('ix_address_record_city'), 'address_record', ['city'], unique=False)
    op.create_index(op.f('ix_address_record_country'), 'address_record', ['country'], unique=False)
    op.create_index(op.f('ix_address_record_normalized_address'), 'address_record', ['normalized_address'], unique=False)
    op.create_index(op.f('ix_address_record_postal_code'), 'address_record', ['postal_code'], unique=False)
    op.create_index(op.f('ix_address_record_state'), 'address_record', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_address_record_state'), table_name='address_record')
    op.drop_index(op.f('ix_address_record_postal_code'), table_name='address_record')
    op.drop_index(op.f('ix_address_record_normalized_address'), table_name='address_record')
    op.drop_index(op.f('ix_address_record_country'), table_name='address_record')
    op.drop_index(op.f('ix_address_record_city'), table_name='address_record')
    op.drop_index(op.f('ix_address_record_address_2'), table_name='address_record')
    op.drop_index(op.f('ix_address_record_address_1'), table_name='address_record')
    op.drop_column('address_record', 'normalized_address')
    # ### end Alembic commands ###
